version: '3.3'

volumes:
  static_value:
  media_value:
  postgres_data:
  
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: nsolntsev/api_yamdb-master-web:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .static:/var/html/static/
      - .media:/var/html/media/  
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    depends_on:
      - web
